version: "3.8"
services:
  mongo: 
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    ports: 
      - "27017:27017"

  metabase:
    image: metabase/metabase
    ports:
      - "3001:3000"
