version: "3.8"
services:
  mongo: 
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    ports: 
      - "27017:27017"
  mongo_test: 
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: testpw
    ports: 
      - "27018:27017"

  metabase:
    image: metabase/metabase:v0.38.0-rc4 # Adds Date ISO string support
    ports:
      - "3001:3000"
